const filters=document.querySelectorAll(".filter"),cards=document.querySelectorAll(".work-card"),menuToggle=document.querySelector(".menu-toggle"),mobileMenu=document.querySelector(".mobile-menu"),modal=document.getElementById("projectModal"),modalImage=document.getElementById("modalImage"),modalTitle=document.getElementById("modalTitle"),modalType=document.getElementById("modalType"),closeButton=document.querySelector(".modal-close"),backdrop=document.querySelector(".modal-backdrop");
function applyFilter(value){filters.forEach(b=>{const active=b.dataset.filter===value;b.classList.toggle("active",active);b.setAttribute("aria-selected",active)});cards.forEach(c=>c.classList.toggle("hidden",value!=="all"&&c.dataset.category!==value))}
filters.forEach(b=>b.addEventListener("click",()=>applyFilter(b.dataset.filter)));
function closeMenu(){mobileMenu.classList.remove("open");mobileMenu.setAttribute("aria-hidden","true");menuToggle.setAttribute("aria-expanded","false")}
menuToggle.addEventListener("click",()=>{const open=mobileMenu.classList.toggle("open");mobileMenu.setAttribute("aria-hidden",!open);menuToggle.setAttribute("aria-expanded",open)});
document.querySelectorAll(".mobile-menu a").forEach(a=>a.addEventListener("click",closeMenu));
document.querySelectorAll(".nav-link").forEach(link=>link.addEventListener("click",()=>{document.querySelectorAll(".nav-link").forEach(x=>x.classList.remove("active"));link.classList.add("active")}));
document.querySelectorAll(".project-trigger").forEach(trigger=>trigger.addEventListener("click",()=>{const card=trigger.closest(".work-card");modalImage.src=card.dataset.image;modalImage.alt=card.dataset.title;modalTitle.textContent=card.dataset.title;modalType.textContent=card.dataset.type;modal.classList.add("open");modal.setAttribute("aria-hidden","false");document.body.style.overflow="hidden"}));
function closeModal(){modal.classList.remove("open");modal.setAttribute("aria-hidden","true");document.body.style.overflow=""}
closeButton.addEventListener("click",closeModal);backdrop.addEventListener("click",closeModal);document.addEventListener("keydown",e=>{if(e.key==="Escape"&&modal.classList.contains("open"))closeModal()});
const revealItems=document.querySelectorAll(".work-card,.section-heading,.capabilities,.availability,.contact");const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.animate([{opacity:0,transform:"translateY(18px)"},{opacity:1,transform:"translateY(0)"}],{duration:500,easing:"cubic-bezier(.2,.7,.2,1)",fill:"forwards"});observer.unobserve(entry.target)}}),{threshold:.08});revealItems.forEach(x=>observer.observe(x));
